AdminBookStoreApp/Controllers/AuthorController.cs
using AdminBookStoreApp.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace AdminBookStoreApp.Controllers
{
    public class AuthorController : Controller
    {
        public IActionResult Index()
        {
            HttpClient client = new HttpClient();
            string URL = "https://bookstoreweb20240707160345.azurewebsites.net/api/Admin/GetAllAuthors";

            HttpResponseMessage response = client.GetAsync(URL).Result;
            var data = response.Content.ReadAsAsync<List<Author>>().Result;
            return View(data);
        }

        public IActionResult Details(string id)
        {
            HttpClient client = new HttpClient();
            //added in next aud
            string URL = "https://bookstoreweb20240707160345.azurewebsites.net/api/Admin/GetAuthorDetails";
            var model = new
            {
                Id = id
            };

            HttpContent content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");

            HttpResponseMessage response = client.PostAsync(URL, content).Result;

            var result = response.Content.ReadAsAsync<Author>().Result;


            return View(result);

        }
        public IActionResult Edit(string id)
        {
            HttpClient client = new HttpClient();
            //added in next aud
            string URL = "https://bookstoreweb20240707160345.azurewebsites.net/api/Admin/GetAuthorDetails";
            var model = new
            {
                Id = id
            };

            HttpContent content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");

            HttpResponseMessage response = client.PostAsync(URL, content).Result;

            var result = response.Content.ReadAsAsync<Author>().Result;


            return View(result);

        }
        public IActionResult Update(Author author)
        {
            HttpClient client = new HttpClient();
            string URL = "https://bookstoreweb20240707160345.azurewebsites.net/api/Admin/EditAuthor";

            HttpContent content = new StringContent(JsonConvert.SerializeObject(author), Encoding.UTF8, "application/json");

            HttpResponseMessage response = client.PostAsync(URL, content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                // Handle the error response, for example, by displaying an error message
                ModelState.AddModelError(string.Empty, "Failed to update author");
                return View(author);
            }
        }

        public IActionResult Delete(string id)
        {

            HttpClient client = new HttpClient();
            //added in next aud
            string URL = "https://bookstoreweb20240707160345.azurewebsites.net/api/Admin/DeleteAuthor";
            var model = new
            {
                Id = id
            };

            HttpContent content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");

            HttpResponseMessage response = client.PostAsync(URL, content).Result;

            var result = response.Content.ReadAsAsync<Author>().Result;
            return RedirectToAction("Index");

        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();

        }
        [HttpPost]
        public IActionResult Create(Author author)
        {
            HttpClient client = new HttpClient();
            string URL = "https://bookstoreweb20240707160345.azurewebsites.net/api/Admin/CreateAuthor";

            HttpContent content = new StringContent(JsonConvert.SerializeObject(author), Encoding.UTF8, "application/json");

            HttpResponseMessage response = client.PostAsync(URL, content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                // Handle the error response, for example, by displaying an error message
                ModelState.AddModelError(string.Empty, "Failed to create author");
                return View(author);
            }
        }

    }
}

AdminBookStoreApp/Controllers/PublishersController.cs
using AdminBookStoreApp.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace AdminBookStoreApp.Controllers
{
    public class PublishersController : Controller
    {
        public IActionResult Index()
        {
            HttpClient client = new HttpClient();
            string URL = "https://bookstoreweb20240707160345.azurewebsites.net/api/Admin/GetAllPublishers";

            HttpResponseMessage response = client.GetAsync(URL).Result;
            var data = response.Content.ReadAsAsync<List<Publisher>>().Result;
            return View(data);
        }

        [HttpGet]
        public IActionResult Edit(string id)
        {
            HttpClient client = new HttpClient();
            //added in next aud
            string URL = "https://bookstoreweb20240707160345.azurewebsites.net/api/Admin/GetPublishersDetails";
            var model = new
            {
                Id = id
            };

            HttpContent content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");

            HttpResponseMessage response = client.PostAsync(URL, content).Result;

            var result = response.Content.ReadAsAsync<Publisher>().Result;


            return View(result);

        }

        [HttpGet]
        public IActionResult Details(string id)
        {
            HttpClient client = new HttpClient();
            //added in next aud
            string URL = "https://bookstoreweb20240707160345.azurewebsites.net/api/Admin/GetPublishersDetails";
            var model = new
            {
                Id = id
            };

            HttpContent content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");

            HttpResponseMessage response = client.PostAsync(URL, content).Result;

            var result = response.Content.ReadAsAsync<Publisher>().Result;


            return View(result);

        }


        [HttpPost]
        public IActionResult Update(Publisher author)
        {
            HttpClient client = new HttpClient();
            string URL = "https://bookstoreweb20240707160345.azurewebsites.net/api/Admin/EditPublisher";

            HttpContent content = new StringContent(JsonConvert.SerializeObject(author), Encoding.UTF8, "application/json");

            HttpResponseMessage response = client.PostAsync(URL, content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                // Handle the error response, for example, by displaying an error message
                ModelState.AddModelError(string.Empty, "Failed to update author");
                return View(author);
            }
        }

        public IActionResult Delete(string id)
        {

            HttpClient client = new HttpClient();
            //added in next aud
            string URL = "https://bookstoreweb20240707160345.azurewebsites.net/api/Admin/DeletePublisher";
            var model = new
            {
                Id = id
            };

            HttpContent content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");

            HttpResponseMessage response = client.PostAsync(URL, content).Result;

            var result = response.Content.ReadAsAsync<Publisher>().Result;
            return RedirectToAction("Index");

        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();

        }
        [HttpPost]
        public IActionResult Create(Publisher author)
        {
            HttpClient client = new HttpClient();
            string URL = "https://bookstoreweb20240707160345.azurewebsites.net/api/Admin/CreatePublisher";

            HttpContent content = new StringContent(JsonConvert.SerializeObject(author), Encoding.UTF8, "application/json");

            HttpResponseMessage response = client.PostAsync(URL, content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                // Handle the error response, for example, by displaying an error message
                ModelState.AddModelError(string.Empty, "Failed to create author");
                return View(author);
            }
        }

    }
}

AdminBookStoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdminBookStoreApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdminBookStoreApp.styles.css" asp-append-version="true" />
    <style>
        body {
            background-color: #fcf8f3; /* second-color */
            color: #333;
            font-family: Arial, sans-serif;
        }

        .navbar {
            background-color: #698474; /* fourth-color */
        }

        .navbar-brand, .nav-link {
            color: white !important;
        }

            .nav-link:hover {
                color: #ffaaa5 !important; /* first-color */
            }

        .footer {
            background-color: #698474; /* fourth-color */
            color: white;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding-top: 20px;
        }

        .row {
            display: flex;
            flex-wrap: wrap;
            margin: 0 -15px;
        }

        .col-3 {
            flex: 0 0 25%;
            max-width: 25%;
            padding: 0 15px;
        }

        .card {
            margin-bottom: 30px;
            transition: transform 0.3s ease-in-out;
            background-color: #fcf8f3; /* second-color */
            border: none;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

            .card:hover {
                transform: scale(1.05);
            }

        .card-img-top {
            height: 350px;
            object-fit: cover;
        }

        .card-body {
            height: 200px;
            overflow-y: auto;
            background-color: #ffd3b6; /* third-color */
        }

        .card-footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            background-color: #698474; /* fourth-color */
            text-align: center;
        }

        .btn {
            margin: 5px;
            color: white;
        }

        .btn-info {
            background-color: #ffaaa5; /* first-color */
            border: none;
        }

        .btn-success {
            background-color: #698474; /* fourth-color */
            border: none;
        }

        .m-3 a {
            color: white;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AdminBookStoreApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                      
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Publishers" asp-action="Index">Publishers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AdminBookStoreApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>