BookStoreApp/BookStore.Web/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookStore.Repository;
using BookStore.Domain.Domain;
using BookStore.Service.Interface;
using BookStore.Service.Implementation;
using System.Security.Claims;
using Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage;

namespace BookStore.Web.Controllers
{
    public class BooksController : Controller
    {
        private readonly IBooksService _booksService;
        private readonly IAuthorService _authorService;
        private readonly IPublisherService _publisherService;
        private readonly IShoppingCartService _shoppingCartService;

        public BooksController(IBooksService booksService, IAuthorService authorService, IPublisherService publisherService, IShoppingCartService shoppingCartService)
        {
            _booksService = booksService;
            _authorService = authorService;
            _publisherService = publisherService;
            _shoppingCartService = shoppingCartService;
        }

        // GET: Books
        public IActionResult Index()
        {
            return View(_booksService.GetAll());
        }

        // GET: Books/Details/5
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var books = _booksService.GetDetails(id);
            if (books == null)
            {
                return NotFound();
            }

            return View(books);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            // Fetch the authors from the database
            var authors = _authorService.GetAll().Select(a => new {
                Id = a.Id,
                FullName = a.FirstName + " " + a.LastName  // Combine first and last names
            }).ToList();

            // Create a SelectList with FullName as the text and Id as the value
            ViewData["AuthorId"] = new SelectList(authors, "Id", "FullName");
            ViewData["PublisherId"] = new SelectList(_publisherService.GetAll(), "Id", "Name");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,Title,BookImage,Price,ReleaseDate,PublisherId,AuthorId")] Books books)
        {
            if (ModelState.IsValid)
            {
                _booksService.CreateNewBook(books);
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_authorService.GetAll(), "Id", "Id", books.AuthorId);
            ViewData["PublisherId"] = new SelectList(_publisherService.GetAll(), "Id", "Name", books.PublisherId);
            return View(books);
        }

        // GET: Books/Edit/5
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var books = _booksService.GetDetails(id);
            if (books == null)
            {
                return NotFound();
            }
            var authors = _authorService.GetAll().Select(a => new {
                Id = a.Id,
                FullName = a.FirstName + " " + a.LastName  // Combine first and last names
            }).ToList();

            // Create a SelectList with FullName as the text and Id as the value
            ViewData["AuthorId"] = new SelectList(authors, "Id", "FullName");
            ViewData["PublisherId"] = new SelectList(_publisherService.GetAll(), "Id", "Name", books.PublisherId);
            return View(books);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, [Bind("Id,Title,BookImage,Price,ReleaseDate,PublisherId,AuthorId")] Books books)
        {
            if (id != books.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _booksService.UpdateExistingBook(books);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BooksExists(books.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_authorService.GetAll(), "Id", "Id", books.AuthorId);

            ViewData["PublisherId"] = new SelectList(_publisherService.GetAll(), "Id", "Name", books.PublisherId);
            return View(books);
        }

        // GET: Books/Delete/5
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var books = _booksService.GetAll();
            if (books == null)
            {
                return NotFound();
            }

            return View(books);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            _booksService.DeleteBook(id);
            return RedirectToAction(nameof(Index));
        }

        private bool BooksExists(Guid id)
        {
            var book = _booksService.GetDetails(id);
            return book != null;
        }

        public IActionResult AddToCart(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = _booksService.GetDetails(id);

            BooksInShoppingCart ps = new BooksInShoppingCart();

            if (product != null)
            {
                ps.BookId = product.Id;
                ps.Book = product;
            }

            return View(ps);
        }

        [HttpPost]
        public IActionResult AddToCartConfirmed(BooksInShoppingCart model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _shoppingCartService.AddToShoppingConfirmed(model, userId);

            return View("Index", _booksService.GetAll());
        }
    }
}

BookStoreApp/BookStore.Web/Views/Books/AddToCart.cshtml
@model BookStore.Domain.Domain.BooksInShoppingCart

<h1>Add Book to Shopping cart</h1>

<div class="row">
    <div class="col-4">

        <form asp-action="AddToCartConfirmed">
            <input type="hidden" asp-for="BookId" />
            <div class="form-group">
                <h5>Book Title : @Model.Book.Title</h5>
             
            </div>

            <div class="form-group">
                <label asp-for="Quantity"></label>
                <input asp-for="Quantity" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Add To Cart" class="btn-info" />
            </div>
        </form>
    </div>
</div>

BookStoreApp/BookStore.Web/Views/Books/Create.cshtml
@model BookStore.Domain.Domain.Books

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Books</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookImage" class="control-label"></label>
                <input asp-for="BookImage" class="form-control" />
                <span asp-validation-for="BookImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublisherId" class="control-label"></label>
                <select asp-for="PublisherId" class ="form-control" asp-items="ViewBag.PublisherId"></select>
            </div>
            <div class="form-group">
                <label asp-for="AuthorId" class="control-label"></label>
                <select asp-for="AuthorId" class ="form-control" asp-items="ViewBag.AuthorId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookStoreApp/BookStore.Web/Views/Books/Delete.cshtml
@model BookStore.Domain.Domain.Books

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Books</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publisher.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookStoreApp/BookStore.Web/Views/Books/Details.cshtml
@model BookStore.Domain.Domain.Books

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div class="container mt-4">
    <div class="row">
        <div class="col-md-4">
            <img class="img-fluid" src="@Model.BookImage" alt="Book image" style="height: 350px; object-fit: cover;">
        </div>
        <div class="col-md-8">
            <div class="card" style="height: 100%; overflow: hidden;">
                <div class="card-body" style="height: 100%; overflow-y: auto;">
                    <h4 class="card-title">@Html.DisplayFor(model => model.Title)</h4>
                    <p class="card-text"><strong>Price:</strong> @Html.DisplayFor(model => model.Price)</p>
                    <p class="card-text"><strong>Release Date:</strong> @Html.DisplayFor(model => model.ReleaseDate)</p>
                    <p class="card-text"><strong>Publisher:</strong> @Html.DisplayFor(model => model.Publisher.Name)</p>
                    <p class="card-text"><strong>Author:</strong> @Html.DisplayFor(model => model.Author.FirstName) @Html.DisplayFor(model => model.Author.LastName)</p>
                </div>
                <div class="card-footer" style="position: absolute; bottom: 0; width: 100%;">

                    <a asp-controller="Books" asp-action="AddToCart" asp-route-id="@Model.Id" class="btn btn-info">Add to Cart</a>
                    |
                    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
                </div>
            </div>
        </div>
    </div>
</div>

BookStoreApp/BookStore.Web/Views/Books/Edit.cshtml
@model BookStore.Domain.Domain.Books

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Books</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookImage" class="control-label"></label>
                <input asp-for="BookImage" class="form-control" />
                <span asp-validation-for="BookImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublisherId" class="control-label"></label>
                <select asp-for="PublisherId" class="form-control" asp-items="ViewBag.PublisherId"></select>
                <span asp-validation-for="PublisherId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorId" class="control-label"></label>
                <select asp-for="AuthorId" class="form-control" asp-items="ViewBag.AuthorId"></select>
                <span asp-validation-for="AuthorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookStoreApp/BookStore.Web/Views/Books/Index.cshtml
@model List<BookStore.Domain.Domain.Books>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">

    @for(int i=0;i<Model.Count; i++)
    {
        var item = Model[i];
        if(i % 3 == 0)
        {
            @:<div class="row">
        }
        <div class="col-3 m-4">

            <div class="card" style="width: 18rem; height: 35rem; overflow: hidden;">
                <img class="card-img-top" src="@item.BookImage" alt="Card image cap" style="height: 350px; object-fit: cover;">
                <div class="card-body" style="height: 200px; overflow-y: auto;">
                    <h5 class="card-title">@item.Title</h5>
                    <p class="card-text">Author: @item.Author.FirstName @item.Author.LastName</p>
                    <h6>Price: @item.Price</h6>
                    <h6>Release Date: @item.ReleaseDate</h6>
                </div>
                <div class="card-footer" style="position: absolute; bottom: 0; width: 100%;">
                    <a asp-controller="Books" asp-action="AddToCart" asp-route-id="@item.Id" class="btn btn-info">Add to Cart</a>
                    <a asp-controller="Books" asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Details</a>
                </div>

            </div>
        </div>

        if(i % 3 == 2)
        {
            @:</div>
        }
    }
</div>